### ISSUE TITLE
can it be used in tensorflow=1.1x

### ISSUE THREAD

**Issue by stefenmax** [titu1994/tf_SIREN#14]
my original coda is in tensorflow=1.13,and i tried tranforming it in tf2.0.But it is a big work,i just want to use it as a activation,coule give me a simple way to address it?thx

**Comment by titu1994** [comment]
I won't be backporting this to 1.x. You can give it a try though, I do believe Keras support is there in 1.15

**Comment by stefenmax** [comment]
OK THX I will try it in 1.15
