### ISSUE TITLE
Why Sine activation function as a network layer in use?

### ISSUE THREAD

**Issue by ZeHuangFang** [titu1994/tf_SIREN#3]
Thank you for your contribution!

I saw in the SinusodialRepresentationDense layer that the Sine activation function was passed as a network layer? Is there any benefit to doing this?

And what happens if I change it to normal function?

Thank you very much!

**Comment by titu1994** [comment]
Nothing much happens. You can of course use it directly. Keras custom layers like LeakyRelu are however built for activation functions with arguments - here w0. So I used it as a layer.

**Comment by ZeHuangFang** [comment]
Yes, it works fine as a normal function! I plan to extend it to RNN's network, for better signal processing. Thanks again!
