### ISSUE TITLE
different results from "SinusodialRepresentationDense" and "SIRENModel"

### ISSUE THREAD

**Issue by hgwang2018** [titu1994/tf_SIREN#5]
Thanks for the great work, Somshubra!
I tried to use both the Layer class and the Model Class to build the same model structure with exactly the same parameters, and I found that the Model Class (SIRENModel) is consistently better than the model created using the Layer Class "SinusodialRepresentationDense", for at least 10 repeated tests. this makes me realize there must be some difference between my implementation using Layer class and your SIRENModel. However, after reading through your code, I could not figure it out. Please advise if you have time. Thanks!

Here is the code scripts for the three model implementation. the MODEL 3 is consistently better than the other two.

Model 1 using the Layer Class:
*****************************************
ip = tf.keras.layers.Input(shape=[1])
xp = SinusodialRepresentationDense(units = 12,
                                  activation='sine', # default activation function
                                  w0=0.2)(ip)        # w0 represents sin(w0 * x) where x is the input.
xp = SinusodialRepresentationDense(units = 12,
                                  activation='sine',
                                  w0 = 1.0)(xp) 
xp = SinusodialRepresentationDense(units = 12,
                                  activation='sine',
                                  w0 = 1.0)(xp)
xp = SinusodialRepresentationDense(units = 1,
                                  activation='linear')(xp)                                
model = tf.keras.Model(inputs=ip, outputs=xp)
*****************************************

Model 2 using the Layer Class:
***********************************************
w0=1.0
w0_initial=0.2
model = keras.Sequential([
    SinusodialRepresentationDense(units=12, w0= w0_initial),
    SinusodialRepresentationDense(units=12, w0=w0),
    SinusodialRepresentationDense(units=12, w0=w0),
    SinusodialRepresentationDense(units =1, activation='linear')])  
***********************************************
Model 3 using the MODEL Class (always better results):
***********************************************
model = SIRENModel(units=12, final_units=1, final_activation='linear',
                   num_layers=3, w0=1.0, w0_initial=0.2)
***********************************************

**Comment by titu1994** [comment]
SIREN models are very sensitive to initialization and initial input value scale. If you look into the SIRENmodel, you will see it actually used different kernel_initializer for the first layer. That alone significantly changes convergence speed. 

On top of that the bias values are also scaled slightly differently based on first vs last vs intermediate layers.

I suggest directly using SIRENModel for out of the box best defaults, and if you need an MLP model. Otherwise follow the steps of the SIRENmodel exactly in your code and you will reach same scores c

**Comment by hgwang2018** [comment]
I added the "kernel_initializer" for Model 1 and 2, and now it works better.  Thanks a lot!
